## Data url

### Mock URL (combine with mode)
GET http://localhost:7000/mock HTTP/1.1

### Static URL
GET http://localhost:7000/user-service/user/1234567890 HTTP/1.1

### Invoices
GET http://localhost:7000/invoices HTTP/1.1

### Invoices
GET http://localhost:7000/companies HTTP/1.1

## Admin url

### Display routes
GET http://localhost:7000/get-routes HTTP/1.1

### CSV to Json
GET http://localhost:7000/load-csv HTTP/1.1

### Change mode
GET http://localhost:7000/update-mode?mode=test3 HTTP/1.1

